---

# Packages required to build edx-analytics-pipeline
JENKINS_ANALYTICS_EXTRA_PKGS:
  - libpq-dev
  - libffi-dev

# See README.md for variable descriptions

JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: jenkins
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_ID: 'github-deploy-key'
JENKINS_ANALYTICS_GITHUB_USER: 'git'
JENKINS_ANALYTICS_GITHUB_PASSPHRASE: null

JENKINS_ANALYTICS_CONCURRENT_JOBS_COUNT: 2

ANALYTICS_SCHEDULE_SECURE_REPO_URL: null
ANALYTICS_SCHEDULE_SECURE_REPO_DEST: "analytics-secure-config"
ANALYTICS_SCHEDULE_SECURE_REPO_VERSION: "master"
ANALYTICS_SCHEDULE_SECURE_REPO_CREDENTIAL_ID: "{{ JENKINS_ANALYTICS_GITHUB_CREDENTIAL_ID }}"
ANALYTICS_SCHEDULE_SECURE_REPO_MASTER_SSH_CREDENTIAL_FILE: "aws.pem"
ANALYTICS_SCHEDULE_JOBS_DSL_REPO_URL: "git@github.com:edx-ops/edx-jenkins-job-dsl.git"
ANALYTICS_SCHEDULE_JOBS_DSL_REPO_VERSION: "master"
ANALYTICS_SCHEDULE_JOBS_DSL_REPO_CREDENTIAL_ID: "{{ JENKINS_ANALYTICS_GITHUB_CREDENTIAL_ID }}"

ANALYTICS_SCHEDULE_SEED_JOB_NAME: "AnalyticsSeedJob"
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_ID: "ssh-access-key"
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_USER: "hadoop"
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: null
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_FILE: "{{ jenkins_home }}/workspace/{{ ANALYTICS_SCHEDULE_SEED_JOB_NAME }}/{{ ANALYTICS_SCHEDULE_SECURE_REPO_DEST }}/{{ ANALYTICS_SCHEDULE_SECURE_REPO_MASTER_SSH_CREDENTIAL_FILE }}"
ANALYTICS_SCHEDULE_JOBS_DSL_CLASSPATH: |
  src/main/groovy
  lib/*.jar
ANALYTICS_SCHEDULE_JOBS_DSL_TARGET_JOBS: "jobs/analytics-edx-jenkins.edx.org/*Jobs.groovy"

JENKINS_ANALYTICS_CREDENTIALS:
  - id: "{{ JENKINS_ANALYTICS_GITHUB_CREDENTIAL_ID }}"
    scope: GLOBAL
    username: "{{ JENKINS_ANALYTICS_GITHUB_USER }}"
    type: ssh-private-key
    passphrase: "{{ JENKINS_ANALYTICS_GITHUB_PASSPHRASE }}"
    description: github access key, generated by ansible
    privatekey: "{{ JENKINS_ANALYTICS_GITHUB_KEY }}"
  - id: "{{ ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_ID }}"
    scope: GLOBAL
    username: "{{ ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_USER }}"
    type: ssh-private-keyfile
    passphrase: "{{ ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE }}"
    description: ssh access key, generated by ansible
    privatekey: "{{ ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_FILE }}"

ANALYTICS_SCHEDULE_COMMON_VARS: ''
ANALYTICS_SCHEDULE_ANSWER_DISTRIBUTION: true
ANALYTICS_SCHEDULE_ANSWER_DISTRIBUTION_EXTRA_VARS: ''
ANALYTICS_SCHEDULE_COURSE_ACTIVITY_WEEKLY: true
ANALYTICS_SCHEDULE_COURSE_ACTIVITY_WEEKLY_EXTRA_VARS: ''
ANALYTICS_SCHEDULE_IMPORT_ENROLLMENTS_INTO_MYSQL: true
ANALYTICS_SCHEDULE_IMPORT_ENROLLMENTS_INTO_MYSQL_EXTRA_VARS: ''
ANALYTICS_SCHEDULE_INSERT_TO_MYSQL_ALL_VIDEO: true
ANALYTICS_SCHEDULE_INSERT_TO_MYSQL_ALL_VIDEO_EXTRA_VARS: ''
ANALYTICS_SCHEDULE_INSERT_TO_MYSQL_COURSE_ENROLL_BY_COUNTRY: true
ANALYTICS_SCHEDULE_INSERT_TO_MYSQL_COURSE_ENROLL_BY_COUNTRY_EXTRA_VARS: ''

jenkins_credentials_root: '/tmp/credentials'
jenkins_credentials_file_dest: "{{ jenkins_credentials_root }}/credentials.json"
jenkins_credentials_script: "{{ jenkins_credentials_root }}/addCredentials.groovy"

jenkins_connection_retries: 240
jenkins_connection_delay: 1
jenkins_auth_realm:
  name: unix
  service: su
  # Change this default password: (see README.md to see how you can do it)
  plain_password: "{{ JENKINS_ANALYTICS_USER_PASSWORD_PLAIN }}"

# For now only a single seed job is supported, adding more would require
# Ansible 2.+ or converting _execute_jenkins_cli to a module
jenkins_seed_job:
  name: "{{ ANALYTICS_SCHEDULE_SEED_JOB_NAME }}"
  multiscm:
    - scm:
      type: git
      url: "{{ ANALYTICS_SCHEDULE_JOBS_DSL_REPO_URL }}"
      dest: ""
      branch: "{{ ANALYTICS_SCHEDULE_JOBS_DSL_REPO_VERSION | default('master') }}"
      credential_id: "{{ ANALYTICS_SCHEDULE_JOBS_DSL_REPO_CREDENTIAL_ID | default('') }}"
    - scm:
      type: git
      url: "{{ ANALYTICS_SCHEDULE_SECURE_REPO_URL | default('') }}"
      dest: "{{ ANALYTICS_SCHEDULE_SECURE_REPO_DEST | default('') }}"
      branch: "$SECURE_BRANCH"
      credential_id: "{{ ANALYTICS_SCHEDULE_SECURE_REPO_CREDENTIAL_ID | default('') }}"
  dsl:
    gradle_tasks: "clean libs test"
    removed_view_action: IGNORE
    removed_job_action: IGNORE
    additional_classpath: "{{ ANALYTICS_SCHEDULE_JOBS_DSL_CLASSPATH }}"
    target_jobs: "{{ ANALYTICS_SCHEDULE_JOBS_DSL_TARGET_JOBS }}"

