# Configure an instance with the admin jenkins.
- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - aws
    - jenkins_admin
    # This requires an override of the following form:
    # SPLUNKFORWARDER_LOG_ITEMS:
    #   - source: /edx/var/jenkins/jobs/*/builds/*/log
    #     index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-jenkins'
    #     sourcetype: jenkins_build
    #     followSymlink: false
    #     crcSalt: <SOURCE>
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
